default:
  image: python:3.10-bookworm
  
stages:
  - "test"
  - "lint"

before_script:
    - apt-get update && apt-get install libgl1 -y
    - python --version ; pip --version
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt

js-unit-tests:
  stage: test
  image: node:20-bookworm
  before_script:
    - npm --version
    - node --version
  script:
    - CI=true
    - cd web
    - npm install
    - npm test

python-unit-tests:
  stage: test
  script:
    - pytest --junitxml=unit-test-report.xml
  artifacts:
    when: always
    reports:
      junit: unit-test-report.xml

python-code-coverage:
  stage: test
  script:
    - pytest --cov=src/ --cov-report term-missing --cov-report xml:coverage.xml
  coverage: '/(?i)TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
          coverage_format: cobertura
          path: coverage.xml

python-linting:
  stage: lint
  script:
    - ruff check . --output-format=gitlab --output-file=gl-code-quality-report.json
  only:
    - merge_requests
  artifacts:
    reports:
      codequality: gl-code-quality-report.json